### ISSUE TITLE
Mailing list links broken

### ISSUE THREAD

**Issue by leif81** [coreemu/core#105]
The links to the cores-users and core-dev mailing lists in the `README.rst` appear to be broken (or not accessible from the internet).

**Comment by Shatnerz** [comment]
So the links are not working for me either, although I can confirm that they definitely worked in the past.

**Comment by siliconja** [comment]
That website (with access to mailman archives) seems to be down. I just replied to a core-users thread and it worked. So email is working but it seems http is not. I'll contact the site owner to see what's up.

**Comment by siliconja** [comment]
Apparently the https sites are still working:
https://pf.itd.nrl.navy.mil/mailman/listinfo/core-users
https://pf.itd.nrl.navy.mil/mailman/listinfo/core-dev

(Although you may get a security-click through for an untrusted US DoD PKI certificate authority.)

For now I'll update the links to **https** instead of **http**.

**Comment by leif81** [comment]
Thank you.

Worth mentioning for others is that the https fix in the README gets me to the mailman interface now. But then the link *within* mailman to the Archives still uses http and so won't work. Once I realized that I prefixed the address with https and could browse the archive.

e.g. https://pf.itd.nrl.navy.mil/pipermail/core-dev/
