### ISSUE TITLE
Absolute paths to EMANE components

### ISSUE THREAD

**Issue by dw19375** [coreemu/core#155]
Some of the files in daemon/core/emane use hard coded absolute paths to various EMANE XML files in `/usr/share`.  This isn't a problem if EMANE is installed from rpms, but if installed from source with the default `--prefix=/usr/local`, `core-daemon` will fail to start.  A workaround is to install EMANE with `--prefix=/usr` or to create a symlink in `/usr/share` to `/usr/local/share/emane`.

**Comment by bharnden** [comment]
Thanks, I contemplated changing this, but figured it had been this way for years and no one had said anything.

I could look to updating this and leverage a configuration value under /etc/core/core.conf, I would just default it to the core prefix when built and someone could change it if needed.

Otherwise the workarounds you suggested are what has been advised before.

Thanks for the input!

**Comment by andreas-ibm** [comment]
Hah yes, that had been bothering me for years and I just never complained ;-)

**Comment by bharnden** [comment]
Something for this is finally on develop branch.

**Comment by bharnden** [comment]
accounted for on develop
