### ISSUE TITLE
Gnome-terminal warning

### ISSUE THREAD

**Issue by kjrrp** [coreemu/core#166]
Hi,

when starting a terminal (e.g. Tshark, vtysh) from the GUI, two things happen:

1) The new window automatically attach to the gnome-shell terminal which launched core-gui (this is new for me, I use to have an older version of Core) instead of a separate window.

2) The gnome-shell terminal will print this message:
```
# Option “-x” is deprecated and might be removed in a later version of gnome-terminal.# 
# Use “-- ” to terminate the options and put the command line to execute after it.# 
```

Core v5.1 (20180531)

Linux 4.15.0-041500-generic x86_64

Ubuntu 18.04 LTS

**Comment by bharnden** [comment]
1) May be related to changes in commands being used with the move to 18.04, since 18.04 has not been tested specifically yet

2) Same would apply for deprecation warnings for updated software within 18.04

There is Edit->Preferences->Programs->Terminal Program that can be changed or tweaked, that might help you.

**Comment by kjrrp** [comment]
Editing the Terminal Program preferences by adding "--" and removing "-x" as requested fixed the issues.

Thanks a lot.
