### ISSUE TITLE
regression: can't (re)start a map in batch mode

### ISSUE THREAD

**Issue by gsomlo** [coreemu/core#188]
If I start a map using
`$ core-gui --batch basic.imn`
and subsequently try to stop it with
`$ core-gui -c <session-id-from-previous-command>`
any subsequent attempt to start another batch session fails with an error:
`Another session is active.`

It appears that the `core-gui -c <number>` no longer cleans up the session properly, leaving behind some sort of inconsistent state from the perspective of core-daemon.

This used to work throughout 4.8, but I haven't tested it since 5.0 was dropped into the git master branch, so I don't know where it broke, specifically (I know, "git bisect"  should help here, but I'm a bit scared of trying that on the CORE sources :) ). Hoping the attached log file and "basic.imn" topology file will help instantly pinpoint the problem to the real core developers who are familiar with the source!

[core_batch_error.log](https://github.com/coreemu/core/files/2384350/core_batch_error.log)
[basic.imn.txt](https://github.com/coreemu/core/files/2384356/basic.imn.txt)

Thanks,
--G

**Comment by siliconja** [comment]
I recently transitioned my CORE Python script from 4.8 --> 5.2. I was also surprised by this behavior:
```
2018-09-14 13:06:29,201 - INFO - coreemu:is_active - session(33843) checking if active: False
2018-09-14 13:06:29,201 - INFO - corehandlers:finish - no session clients left and not active, initiating shutdown```
Because (in some cases) I wanted my session to continue running after the script ends.

The solution for me, since I subclassed the EmuSession class, was to override the EmuSession.shutdown() handler, and NOT shutdown in certain cases.

I think you're touching on a useful use case here: (1) tell the daemon to start a session, (2) have that session running in the background with no GUI for some time, (3) optionally connect a GUI to check on things/interact, (4) disconnect the GUI but leave the session running (it used to prompt you about this), (5) at some later point, terminate the session using the Sessions GUI window, or core-cleanup.

**Comment by gsomlo** [comment]
On Fri, Sep 14, 2018 at 09:23:06PM -0700, bharnden wrote:
> Looks like an issue with forgetting to remove the session when the batch delete
> command is sent. Modifying it locally to formally remove the session seems to
> resolve the provided example.
> 
> Can get this fix added in maybe see if anything else pops up and roll that into
> a fix release, or can just hot patch to master.

Commit against the master branch that eventually ends up being part of
the next release is great as far as I'm concerned -- but do whatever
makes sense for the project's development flow! (as long as there's a
way to grab a copy of the patch from somewhere in the interim, that is :) )

Much appreciated!
--Gabriel
