### ISSUE TITLE
[BUG] Error when right clicking OVS node during emulation

### ISSUE THREAD

**Issue by GarettFox** [coreemu/core#271]
**Describe the bug**
Whenever I right click an OVS switch node while running an emulation, I get an error.

**To Reproduce**
1. Place an OVS switch node into a CORE network
2. Start the emulation
3. Right click the switch node
4. See error:
```
invalid command name "OVS.shellcmd"
invalid command name "OVS.shellcmd"
    while executing
"[typemodel $node].shellcmd $node"
    (procedure "button3node" line 172)
    invoked from within
"button3node .c 461 312 """
    (command bound to event)
```

**Expected behavior**
The drop-down menu for Configure, Shell Window, Services, etc. appears on the OVS node

**Desktop (please complete the following information):**
 - OS: Kali GNU/Linux Rolling
 - CORE Version 5.3
 - EMANE Version 1.2.3

**Comment by bharnden** [comment]
I know this was experimentally added, it is very possible they did not account for all GUI interactions. Potentially this node may go away.

Alternatively you can try leveraging OVS mode, which would use OVS bridges instead of Linux bridges when connected nodes. There are discussions of having this possibly be the default moving forward.

**Comment by bharnden** [comment]
Will remove node in next release, functionality was replaces by using an OVS service on a node
