### ISSUE TITLE
[BUG]  No import terminal

### ISSUE THREAD

**Issue by NatanielAfonso** [coreemu/core#304]
Terminal Export Issues

When executing commands in the container shell such as "clear" or "nano", it returns an unrecognized terminal error message.

Already installed xterm and selected in "preferences" but the error persists.

in the container if I execute the command "export -p" it doesn't really matter the host host terminal and the problem is only solved when I run in the container "export TERM = xterm"

Does anyone know how to solve?

**Comment by NatanielAfonso** [comment]
![nn](https://user-images.githubusercontent.com/56442173/66656615-bc0d4c80-ec14-11e9-8e37-5d7735669650.PNG)

This is an example of how I solve the problem to execute commands on terminals correctly.

I'm using the latest version in git "5.5.0

**Comment by bharnden** [comment]
I can only assume the way in which core-daemon is running doesn't have a TERM environment variable. Since typically this gets inherited for each node container.

You can run env inside a container to print what you have.

On Ubuntu, I get that by default, potentially another distribution you may be trying does not?

**Comment by bharnden** [comment]
let me know if there is anything to follow up with

**Comment by NatanielAfonso** [comment]
Hello, I've been in a few days, but now I'm coming back and continuing with my problem!

I am using lubuntu version 19.04 and when I type "env" on a node, a terminal variable is not returned. Can you help me?
