### ISSUE TITLE
Reporting Error When Using Custom EMANE Model via Pytthon Script

### ISSUE THREAD

**Issue by ChengDaHaI** [coreemu/core#356]
**Describe the bug**
I am following [Example Model](https://github.com/coreemu/core/blob/master/daemon/examples/myemane/examplemodel.py) to define a custom EMANE model (basicaly the RFPipe model with "precomputed" propagationmodel ). However, in my python script example, it report

> File "/usr/lib/python3.6/dist-packages/core/config.py", line 386, in set_model
    self.set_model_config(node.id, model_class.name, config)
  File "/usr/lib/python3.6/dist-packages/core/config.py", line 336, in set_model_config
    raise ValueError("%s is an invalid model" % model_name)
ValueError: emane_rfpipecustom is an invalid model

The related code is 
> emane_network = session.add_node(_type=NodeTypes.EMANE, node_options=options, _id = 100)
    session.emane.set_model(emane_network, Rfpipe_custom)

I think the problem is that i do not know how to add my cutom emane model to `self.models` in `ModelManager` class in [config.py.](https://github.com/coreemu/core/blob/master/daemon/core/config.py).

**Desktop (please complete the following information):**
 - OS: [ Ubuntu 18.04]
 - CORE Version: [ 5.5.2]
 - EMANE Version: [1.2.3]

**Comment by bharnden** [comment]
Maybe you have other plans. But you can configure the EMANE models themselves to use different settings, instead of needing to create a customized model.

The customized models are really more so for someone who has written a custom model in EMANE itself and needs a way to bring that into CORE.

You can view all the EMANE configuration options you have available for a given model with the GUI.
