### ISSUE TITLE
[FEATURE] Enable staticd by default

### ISSUE THREAD

**Issue by asabolansky** [coreemu/core#397]
We work with empty imn topologies and use scripts that restore the configuration of the routers through the vcmd command.

We detect that the staticd service is only enabled if a static route is detected in the configuration.

Therefore, it would be desirable that in the file /usr/local/lib/python3.6/dist-packages/core/services/frr.py the staticd service can be enabled by default.

Thank you

**Comment by bharnden** [comment]
@sei-gsomlo @apwiggins You both seem have the FRR familiarity, any thoughts on having it on by default being an issue?

**Comment by apwiggins** [comment]
@bharnden @sei-gsomlo 
There shouldn't be an issue with enabling staticd=yes.  The original daemons file template likely dates back a few FRR versions and can be updated to version 7.2 (current).

Current example template is here:
https://github.com/FRRouting/frr/blob/7925535457e1adbaf2f064e7f3d446fb9bedc353/doc/user/setup.rst

**Comment by sei-gsomlo** [comment]
In https://github.com/coreemu/core/commit/d2fe35279793a858ab88fe5324fed41edae20926 I proposed that `staticd` be started conditionally simply to fit with the model of all the other surrounding daemons (except for `zebra`). All routing daemons are only started if the (unified) config contains a `router <foo>` statement, so I figured let's stick with that model and start `staticd` only if the config contains any `ip route ...` statement(s).

On one hand, I don't think it's a problem to have `staticd` fired up unconditionally, right after `zebra`.

On the other hand, my follow-up question would be: "What if one needs to insert an entire `router bgp` block via vcmd? How would you then fire up `bgpd` on-demand, in preparation for that? What are the tradeoffs for/against doing that same thing to fire up staticd on-demand (maybe even using vcmd itself)? Or would you rather start *all* routing daemons by default, just in case?"

I don't think any possible answer to any of the above would be _wrong_ per se, it's all just a matter of aesthetics and tradeoff re. whatever host-side resources idle daemons might consume.

`<rant>`Why oh why did the FRR people have to split off `staticd` from `zebra`, look at the kind of mental gymnastics we now have to deal with because of that :D`</rant>`

**Comment by apwiggins** [comment]
I think that your model is good.  I did consider this approach initially.

The case that concerned me is the explorer who is initially trying router
configs via the vtysh.  It's just easier if all the daemons are available.
Since FRR is finicky about config statement order, sometimes the only way
to generate the proper config order is via vtysh.

Is there anything that breaks functionality or is super sub-optimal if all
the daemons are available by default?

Cheers,

Phil
902-574-7880

**Comment by sei-gsomlo** [comment]
> Is there anything that breaks functionality or is super sub-optimal if all the daemons are available by default?

I'm not an FRR developer (in fact, I just realized that "it's the new Quagga, whose upstream is mostly dead", and decided to migrate to it, only to learn about `staticd` :) ) -- so the answer is "I have no idea re. sub-optimality". I don't think there'd be any actual *breakage* if all daemons were started. I guess it depends on just how much in terms of host-side resources is wasted by having idle routing daemons sitting around doing nothing much...

This leads me to my immediately next thought: Shouldn't `zebra` be responsible for *automatically* starting `staticd` or any of the `<router>d` daemons whenever vtysh attempts to add the first static route, or the first `router <protocol>` statement ? I realize this is more of a feature request for upstream FRR, but at the moment I don't have the spare cycles to pursue it directly with them...

But think about how nice that would be: all you'd *ever* have to deal with would be to fire up `zebra`, which then would start whatever daemons are necessary, and only when necessary, on demand! Kinda like the *original* thing we're trying to emulate ;)

**Comment by apwiggins** [comment]
I had a chance to look at a live router this morning.  So, only the router instances started by zebra are available as running processes. In the example below, only zebra and babeld are running.  So trying to set configurations for bgpd doesn't work (i.e., bgpd was set to yes in FRRZebra.generateFrrDaemons() ) and it similarly wouldn't work for staticd if added as a daemon.
```
n4(config)# router bgp
bgpd is not running
n4(config-router)# ^Z
n4# sho daemons 
 zebra babeld
```

**Comment by bharnden** [comment]
So at the end of the day if its enabled and has an empty configuration, this may help achieve what is desired?

**Comment by apwiggins** [comment]
> So at the end of the day if its enabled and has an empty configuration, this may help achieve what is desired?
Yes, an empty config in frr.conf should launch staticd by default.

As soon as the keyword for the router type 'bgp', 'ospf', etc is seen in the config (frr.conf), then the specific router gets launched by the FRR startup script (i.e., there's a bash for-loop that launches each daemon process along with zebrad).  So, presumably, if there is a default static config, then staticd will get launched.

This snippet will need to be modified to include all of the possible routers (including static).  This looks like my original script where I was just testing a few items.  It should be expanded to encompass all the permitted router daemon types.
===
https://github.com/coreemu/core/blob/master/daemon/core/services/frr.py#L214
===
    for r in rip ripng ospf6 ospf bgp babel isis; do
        if grep -q "^router \\<${r}\\>" $FRR_CONF; then
            bootdaemon "${r}d"
        fi
    done

**Comment by asabolansky** [comment]
I prefer to leave the default active services on the routers (bgp, ospf6, ospf, static) since I use the vcmd shell to restore the settings made from the vtysh.

**Comment by asabolansky** [comment]
We use two scripts. One to save the topologies before turning it off and another to
restore it once powered on.

This is the Github repository https://github.com/RYSAEI/SaveRestoreScripts

**Comment by bharnden** [comment]
Not sure if this resulted in something that would specifically make sense to do in regards to this. I am not familiar enough with this case to really say otherwise.

If there is something that would be beneficial to do in the general sense, can take a look, otherwise this can probably be closed.

**Comment by bharnden** [comment]
closing with change from @apwiggins , if anything further is needed. Let us know.
