### ISSUE TITLE
[FEATURE] Add an optional argument for core-pygui to specify which session to connect

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#482]
Right now when there is multiple session running in the backend, if run the core-pygui, you will need to choose which session to connect inside the gui. If we can have an argument for this situation, like `core-pygui -s 1`, I guess we can better automate this frontend-backend interaction.

Speaking of this, if I build a network in python, what's the best practice to utilize the CORE GUI to visualize the topology/info? I checked some previous issues and it seems like we need to run `sudo core-daemon` first and then use grpc client to connect to it. Then what's the difference between this method and the core-pygui?

**Comment by bharnden** [comment]
On the first part, I don't think a couple clicks to decide if you want to join an existing session or create a new one is really that much trouble to try and change the current process. It also helps provide users who may not realize they left a session running, that it exists.

The **core-daemon** is the backend server for handling gRPC and older TLV API messages, this needs to be running for either of the GUIs (core-gui or core-pygui) to connect to and interact with sessions created using those methods.

**core-gui** is older TCL Tkinter GUI that is not planned to be maintained or updated in the future and uses the older TLV API.

**core-pygui** is intended to be the replacement python Tkinter GUI that uses the gRPC API and will be updated and have newer or refined features to account for any changes that may occur in the future.

In the second part by you saying "If I build a network in python" and you creating a session directly within python code and not using an API, then there is no way to get that to appear in a GUI, without using the hack "Execute Python Script" option in a GUI, but that also requires the script to account for this hack case.

You could write a python script that leverages the gRPC API to connect to the core-daemon and create a session, this would allow it to appear and be interacted with, in the GUI if desired.

You can also just drag and drop the session you want to create and save that to an XML file for convenience to recreate later, but it all really depends on what you are trying to do. Since a lot of these interactions can be fairly open ended, there are very different ways a problem could be approached.

**Comment by siliconja** [comment]
I wouldn't say there is no way to attach the GUI to a Python script.

The trick is to write a script the creates a Session. In my scripts I add a `--gui` flag that automatically tells the `core-daemon` to execute the script, which creates a Session and adds it to its session list; and then it automatically launches the GUI. 

This snippet is run to tell the daemon to execute this script:

```
    sendmsg_cmd = f"coresendmsg REGISTER flags=ADD EXECUTE_SERVER=\""
    sendmsg_cmd += os.path.abspath(sys.argv[0]) + " "
```

Here is how I instantiate a Session, assuming I've subclassed MySession as a Session:


```
    if "coreemu" in globals():
        # attached to core-daemon and/or launched this from GUI
        coreemu = globals()["coreemu"]
    else:
        # invoked as standalone Python script
        coreemu = CoreEmu()

    session = coreemu.create_session(_id=options.session_id, _cls=MySession)
    session.name = os.path.basename(sys.argv[0])
    session.filename = os.path.abspath(sys.argv[0])
```

That will add the session to the daemon.

Note that I invoke my script as non-root, which communicates with core-daemon running as root, to re-run the script as root; GUI is launched as non-root.

**Comment by bharnden** [comment]
I would advocate avoiding all usages of anything related to TLV APIs, like coresendmsg etc. Since these will hopefully all go away with time.

I believe this same case should work using the gRPC execute script API: https://github.com/coreemu/core/blob/e0842197e389f3f14c73dc5db6cc26f78e665f62/daemon/proto/core/api/grpc/core.proto#L166

The **__name__** variable within the script will change and be different, than **__main__** when ran directly and can be used as a differentiation, if desired.

**Comment by siliconja** [comment]
I'll have to transition to using this gRPC ExecuteScript...

I would not call this ExecuteScript nor the TLV API execute-script method a hack. :) 

It is a useful and powerful feature to programmatically generate and run headless topologies or optionally attach the GUI. My use case is a protocol self-test suite that runs about 40 different scenarios nightly. If we encounter a test failure, a developer can re-run the script using the same parameters plus the `--gui` option to get an interactive debugging environment.

**Comment by bharnden** [comment]
Ya that makes sense.

More directly you would have to maintain code to either do gRPC or run direct python, but these provides a singular way to achieve both.

It is an odd case in how we have to abuse injecting the script within the code to achieve it, but I don't know that there is any other easy way at the moment.

Potentially the part the runs the script could always provide sometime of gui param, or make the grpc more open ended to allow the user to provide whatever they want.
