### ISSUE TITLE
Build from Source does not register the python API

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#497]
I am trying to update to the develop branch, but somehow core is still not available in python. I tried both the install.sh and the bootstrap.sh/make install stuff, no error duing the installation. So I wonder what extra procedures should I take?

**Comment by bharnden** [comment]
If you are switching to develop, first make sure whatever was previously installed has been uninstalled.

Then, you should be able to run the following from the root of the repo:
```shell
./install.sh
```

Then, you should be able to run the main scripts as normal (core-daemon, core-pygui, etc).

But, if you are trying to run your own script in COREs python environment (since it is setting up and installing into a virtual environment). You would need to run it in that context and there are a few ways to do it. These are noted on the install doc on the develop branch.

https://github.com/coreemu/core/blob/develop/docs/install.md#running-user-scripts

**Comment by mzy2240** [comment]
Thanks! Is there a document about how to correctly/cleanly uninstall the previous version?

**Comment by bharnden** [comment]
If you ran `sudo make install` then `sudo make uninstall` before changing branches etc.

If you had installed from package, uninstall the package.

That should cover it more or less. The new install does a couple quick checks to try and catch old installs, but should be fine.

**Comment by mzy2240** [comment]
Previously I used the package (.deb) to install and the CORE python API will be automatically installed into the system python. So if I want to install the develop version, how can I install the CORE into the system python, or any other specified venv, instead of a new venv?

**Comment by mzy2240** [comment]
> That should cover it more or less.

What if I use `./install.sh` to install?

**Comment by bharnden** [comment]
The intent at the moment is for it to have it's own environment to avoid dependency conflicts, among other things. There is not a plan for it to go into the system python for such reasons.

There is also not a plan at the moment to allow specifying a targeted venv, but if poetry supports it, it could potentially be possible. Otherwise you can always add whatever you like to the virtual environment.

Prior `./install.sh` used `sudo make install`

**Comment by mzy2240** [comment]
Yeah I fully understand, but then why installing from the deb will have CORE installed in the system python?

**Comment by bharnden** [comment]
There will be no more packages in this new approach, the packages are from older releases.

**Comment by mzy2240** [comment]
> There will be no more packages in this new approach, the packages are from older releases.

The one show up in my system python is version 6.5.0. I guess this is the latest release.

**Comment by bharnden** [comment]
Yes and the develop branch will be the next release (7.0.0), so 6.5.0 is an older release in this context.

**Comment by mzy2240** [comment]
Oh ic. I really hope we can still maintain the option to save it to the system python.

**Comment by bharnden** [comment]
Why would this be desired? What could you not do?

I would imagine everything can still be done, with a slightly different approach to the situation. Polluting the system python with various dependencies etc, in general would want to be avoided. It is an issue as well for distributions that do not provide proper packages for various python dependencies, resulting in 2 different things managing what is installed (apt/dnf/yum and pip).

**Comment by mzy2240** [comment]
Yeah cause I have the PTSD to find the location of the venv, also that means for some other packages that are not very friendly to be installed in venv I have to figure out a way to install them in the same core vm.

**Comment by bharnden** [comment]
* Poetry provides command line options for finding the venv if you need that information
* You do not need to know it if leveraging the invoke run task as it will help on that part for you
* You can set to the venv shell if needed to avoid that altogether
* You can install packages inside the venv using pip as one normally would if needed

What is not friendly to install?

```shell
cd daemon

# print out the venv info
poetry env info

# print out the venv path directly
poetry env info -p

# install through poetry directly
poetry run pip install <package>

# enter shell and install
poetry shell
pip install <package>
```

**Comment by mzy2240** [comment]
Thanks! This is my first time knowing this poetry, now everything makes sense.
