### ISSUE TITLE
translation from local XY node position to LAt Lon for SD3D is not correct

### ISSUE THREAD

**Issue by martin20082018** [coreemu/core#561]
**Describe the bug**
I've done a small model with 3 cars, an ns2 mobility script a wallpaper with 2024x2024 px.
If I run this with the old **old CORE version: 5.2.2 --> it works as expected.**
The car (node4) drives on the street. 
It's initial position in SDT3D is **Lat:51,0682 Lon:12,8751**
In CORE the initial position is; **X: 75 Y:1824** even the position in the Core canvas is not correct - it doesn't matter, but the translation to LAT LON in SD3D is correct.

With the **new CORE version 7.4.0** (develop branch)
the translated LAT LON position is:
**LAT: 51,1018 LON: 12,8688** ==> and this is wrong...

**To Reproduce**
1. load attached model: **TEST4_3_CORE7_5_0_develop.imn**
2. go to the WLAN node and select the scene file : **test.scen**
3. set wallpaper to **huhu2_mod4.jpg**
4. and modify the values for canvas size and scale according the attached screenshot: **canvas_size_and_scale.png**
3. run sdt3d.sh 
4. check the LAT LON positions

**Expected behavior**
node4 XY position X: 75 Y:1824 is correctly translated to Lat:51,0682 Lon:12,8751 but it doesn't.

**Screenshots**

**Desktop (please complete the following information):**
    - Ubuntu 18.04
    - CORE Version: 7.4.0
    - EMANE Version 1.2.7

![Canvas_size_and_scale](https://user-images.githubusercontent.com/51402326/111449632-db64af00-870f-11eb-97a2-686bdcc76a0b.png)
[TEST4_3_CORE7_5_0_develop.imn.txt](https://github.com/coreemu/core/files/6155380/TEST4_3_CORE7_5_0_develop.imn.txt)
[test.scen.txt](https://github.com/coreemu/core/files/6155381/test.scen.txt)
![huhu2_mod4](https://user-images.githubusercontent.com/51402326/111449859-136bf200-8710-11eb-9111-19e1f82959af.jpg)

best regards,
Martin

**Comment by bharnden** [comment]
Is it wrong because it is different than before or actually wrong?

There was a switch at some point to leverage a different library to allow rough translations for the entire earth at once, but it is not a perfect answer as the scaling is not factored in differently for x and y, there may also be imperfections in how the translation is occurring.

I would like to get away from translating altogether. COREs view is poor for showing geo, only using bad mockups, while most will look to use something like SDT as you noted. Instead x/y and lon/lat should be two separate pieces of information.

You can drive movement directly with lon/lat, which may give you the specific control you desire. This would currently have to be done over the gRPC API. 

The translations live here if you have any insights in correcting it for all cases: https://github.com/coreemu/core/blob/master/daemon/core/location/geo.py

**Comment by martin20082018** [comment]
I took a while, but I changed the geo.py as you proposed. 
I check the correct calculation for a location in Europa, one location on the west coast in the US and one location in Australia. All of them worked fine with SDT3D. SDT3D is my "main" visualization tool. 
(The location on the wallpapers is still not correct - but this the case since I started working with CORE 2 years ago... this might have a different root cause.)

[geo.odt](https://github.com/coreemu/core/files/7162008/geo.odt)

I copied the Python files in  **odt** files.

Test programs:
[test_main.py.odt](https://github.com/coreemu/core/files/7162075/test_main.py.odt)
[test_mobility.odt](https://github.com/coreemu/core/files/7162049/test_mobility.odt)

**Comment by bharnden** [comment]
Yes the wallpaper location is currently expected to not be exactly accurate and is considered the wrong tool for the job. Using SDT or another visualization tool designed for geospatial data, is the way to go.
