### ISSUE TITLE
[BUG] tdma error in docker container

### ISSUE THREAD

**Issue by ISO497** [coreemu/core#731]
**Describe the bug**
Recently, I installed core 9.0.1 and emane 1.4.1 with Dockerfile. It worked well with other models but the TDMA model went wrong with Alter as 'exception occurred when running RUNTIME_STATE state hook: <bound method Session.runtime_state_hook of <core.emulator.session.Session object at 0x7f23e0358790>>'

I did not change any configuration and all arguments were set as default values.

**To Reproduce**
1. follow the steps in http://coreemu.github.io/core/install.html to install core with dockerfile
2. create two MDR nodes
3. create one EMANE node
4. link two MDR nodes to EMANE node respectively
5. click 'start session'
6. see alters(1) as 'exception occurred when running RUNTIME_STATE state hook: <bound method Session.runtime_state_hook of <core.emulator.session.Session object at 0x7f23e0358790>>'

**Expected behavior**
The TDMA models can work.

**Screenshots**
![image](https://user-images.githubusercontent.com/68182991/209422920-f1434dd8-2d5d-4de1-a166-b096a3c0361f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.1
 - EMANE Version 1.4.1

**Additional context**
By the way, could you teach me how to get the output of core-daemon if I run it in docker container? thanks

**Comment by bharnden** [comment]
Hard to say without seeing the exact error. You could open a shell in the Docker container, kill the `core-daemon` process.

`pkill -f core-daemon` or whatever you like.

Then run the daemon manually in your shell and see the output for the specific error.

**Comment by bharnden** [comment]
turns out it is an environment issue related to the emane tdma script.

You can resolve it by doing the following in the container and running the daemon with the virtualenv activated.
```shell
. /opt/core/venv/bin/activate
core-daemon
```

**Comment by jhonzy0928** [comment]
If not, I had a thought that docker or other VM systems would probably be unable to use the emane TDMA model due to insufficient resources.

**Comment by bharnden** [comment]
> If not, I had a thought that docker or other VM systems would probably be unable to use the emane TDMA model due to insufficient resources.

Nope, docker containers and VMs would be limited by the resources they have access to, which could be all resources of the host.

**Comment by jhonzy0928** [comment]
On my server, I also experience this problem when the number of TDMA nodes is large (hundreds level), and core-daemon is reporting an error as shown below. When I tried the solution you gave, I found that there was no core directory in the opt directory. I think core was installed in a virtual environment, which is fundamentally different from the container. And core can run at least 64 nodes, so what are the environmental problems with this emane TDMA script? In an engineering environment I might not understand this bug right now.
![微信图片_20230420164116](https://user-images.githubusercontent.com/54539693/233310651-e50f816b-81de-4fbe-9d15-3dc7377c0d68.png)
![微信图片_20230420164128](https://user-images.githubusercontent.com/54539693/233310703-4464a061-fa18-443c-bcaf-b12651433359.png)

**Comment by bharnden** [comment]
Please only post errors from the `core-daemon` the GUI side does not help. In this case it sounds like you are using a Docker container. Before running the daemon you should try formally activating the virtual environment.

`source /opt/core/venv/bin/activate`

**Comment by jhonzy0928** [comment]
![微信图片_20230420164128](https://user-images.githubusercontent.com/54539693/233419400-fd4123fa-38a4-450b-801b-77037975538d.png)
I am very sorry that I forgot to emphasize that this picture is the screenshot of the error reported by core-dameon. I only captured the part of the error reported. From the picture, the error is the same as the GUI. Of course, if you can't locate the error correctly, I may give you further details.
Secondly, I am not running directly on doker, but directly on linux system on the server, I think it doesn't seem to make much difference, or I didn't understand exactly what you meant, next I will follow your instructions and give you feedback. Thank you for your reply.

**Comment by jhonzy0928** [comment]
![微信图片_20230421104607](https://user-images.githubusercontent.com/54539693/233528628-eff28906-3771-4f31-942c-1b5463390ee0.png)
Maybe I made a very stupid mistake, thank you very much for reminding me.
When I ran the gui for the first time, I had the error shown in Figure 1, and I chose to ignore it and continue running it, as this error occurs from time to time and does not affect subsequent tests. The second time I ran the gui, I ran sudo core-daemon & in the background, or I ran core-daemon ahead of time, and the error was shown in Figure 2 below.
From a core-daemon point of view, no matter what my gui was running, the errors were constant. This seems to introduce a different error than core-gui.
In addition, my system is not in the file/opt/core/venv/bin/activate, because my version of the system core (8.2.0) different?
![微信图片_20230421104607](https://user-images.githubusercontent.com/54539693/233528612-a5ffc3f5-3d65-4827-bd57-1c5fe848edf5.png)

**Comment by jhonzy0928** [comment]
Maybe I made a very stupid mistake, thank you very much for reminding me.
When I ran the gui for the first time, I had the error shown in Figure 1, and I chose to ignore it and continue running it, as this error occurs from time to time and does not affect subsequent tests. The second time I ran the gui, I ran sudo core-daemon & in the background, or I ran core-daemon ahead of time, and the error was shown in Figure 2 below.
From a core-daemon point of view, no matter what my gui was running, the errors were constant. This seems to introduce a different error than core-gui.
In addition, my system is not in the file/opt/core/venv/bin/activate, because my version of the system core (8.2.0) different?
![微信图片_20230421104607](https://user-images.githubusercontent.com/54539693/233528825-d5410676-2f94-467f-b071-4626d0120deb.png)
![微信图片_20230421104559](https://user-images.githubusercontent.com/54539693/233528885-a069e472-74de-489d-8264-cb7e0388029d.png)
