### ISSUE TITLE
[BUG] distributed emane with docker

### ISSUE THREAD

**Issue by ISO497** [coreemu/core#732]
**Describe the bug**
Recently, I installed core 9.0.1 and emane 1.4.1 with Dockerfile. 
I created two containers in the same subnetwork to try distributed emulation, but some error occured.
When I allocated 5 or less nodes to the distributed server, it seemed work well. But when I allocated over 5 nodes, the error message appeared.
Installation and distributed emulation both followed the instructions. 

**To Reproduce**
1. follow the steps in http://coreemu.github.io/core/install.html to install core with dockerfile
2. create two containers and add them to the same subnetwork
3. follow the steps in http://coreemu.github.io/core/distributed.html to try distributed emulation
4. assigned 6 nodes to core-3
5. start session and and it failed, occured connect failed error, and no alters occured

**Expected behavior**
The distribution emulation still works with over one hundred nodes assigned to other server

**Screenshots**
created 16 MDR nodes and 1 EMANE node, EMANE model is set as rfpipe, started session and it worked
![9ee7c93afb437cc5ecc0634ed1a86a1](https://user-images.githubusercontent.com/68182991/209437517-94b1559f-df80-4c0a-8ac6-fc573d8773f6.png)
assigned 5 nodes to core-3, start session and and it worked
![19db742fd4eb113c428ebae26d77c51](https://user-images.githubusercontent.com/68182991/209437569-cbcd3843-3ebb-4cc1-93f9-d2ad37115d22.png)
assigned one more nodes to core-3, start session and and it failed, occured connect failed error, and no alters occured
![f441266c072cfd1ffdd29a0a9fcd47b](https://user-images.githubusercontent.com/68182991/209437621-68781b8e-2658-4c69-863c-7a4ff0c083e0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.1
 - EMANE Version 1.4.1

**Additional context**
By the way, could you teach me how to get the output of core-daemon if I run it in docker container? thanks

**Comment by bharnden** [comment]
Hard to say offhand, the daemon logs would be better to help indicate the issue.

As noted in the other issue, you can kill the daemon process and run it yourself. A quick look points to `docker logs` or `docker service logs` may be useful instead of what I noted.

Also running distributed amongst containers is not vetted well, so there may be issues, but would be good to determine the cause.

**Comment by bharnden** [comment]
The connect error in your pictures is due to the MaxConnections limit for SSH configured on the distributed node you are connecting to, if you update the number within reason, you can avoid this case.

Also to note EMANE is very CPU intensive (when running traffic) and large numbers of nodes would require significant resources.

**Comment by jhonzy0928** [comment]
I've had this problem before, just change the `/etc/ssh/sshd_config` file and uncomment the `#MaxSessions`.
