### ISSUE TITLE
[BUG]Ubuntu 22.04 install fails at inv install

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#766]
**Describe the bug**
I install CORE on Ubuntu 22.04 but it cannot open and shows there is no command : core-gui. Then I uses inv uninstall and try to reinstall CORE. I use script method to install CORE on Ubuntu22.04. It fails at step inv install and shows:
![image](https://user-images.githubusercontent.com/101703577/220903620-6127783d-921e-4f50-949f-94bf4e350928.png)
I try to delete opt/core and then input inv uninstall and inv install but it doesn't work. 
![image](https://user-images.githubusercontent.com/101703577/220904248-0c660dcc-def9-46c8-bd64-dfd2a180bf3a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]

**Comment by bharnden** [comment]
You can pass `-v` to the install command to help print out what is going on. I believe this is the issue related to needing a newer version of the `fabric` library to be installed due to incompatibility with python 3.10+. You can use an older version of python and all the nuance that comes with that, use an older version of Ubuntu, or update the fabric library. This will be updated in the next bugfix release.

**Comment by bharnden** [comment]
You can show me the output to confirm that is the issue, when you pass `-v`.

**Comment by jxGui** [comment]
After I input command inv install -v, it shows:
![image](https://user-images.githubusercontent.com/101703577/221362976-7c857f12-74bd-42ef-aa51-483d14baeded.png)

**Comment by bharnden** [comment]
this is likely specifically related to the `invoke` dependency, this is fixed in latest release.
