### ISSUE TITLE
[BUG] Docker container: core starts but does nothing

### ISSUE THREAD

**Issue by rsaSantos** [coreemu/core#770]
**Describe the bug**
I have followed the steps in "https://coreemu.github.io/core/install.html#dockerfile-based-install". When I open core-gui and press the run button, nothing happens. No error is thrown in the console. The bar at the bottom of the gui slides forever until I shutdown the program.

**To Reproduce**
1. Follow the steps in "https://coreemu.github.io/core/install.html#dockerfile-based-install"
2. Open one terminal with "sudo docker exec -it core core-daemon"
3. Open another terminal with "sudo docker exec -it core core-gui"
4. Open the sample.xml
5. Press the start button.

**Expected behavior**
It was supposed to run the sample topology. It does nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/58313662/225097096-753db5f1-30cc-48a9-9f58-03a3883e3505.png)
![image](https://user-images.githubusercontent.com/58313662/225097217-086d9b4d-285e-4375-ae47-3939debd8ed0.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 22.0.4
 - CORE Version v9.0.2
 - EMANE Version Not installed

**Comment by bharnden** [comment]
Have you tried something very simple as a starting point? Instead of diving into a larger scenario? One node, 2 nodes linked together?

I also have never vetted Manjaro as the real host, even given that you running out of a Docker based case, it may possibly be related in some way. I do not see any real errors in your output, so its hard to say at face value.

**Comment by rsaSantos** [comment]
Yes, I've tried with only one node, it has the same behavior. And also with 2 nodes linked together. Also, the AUR version is not building due to an assertion error (assert get_changelog_url('Alabaster') == 'https://raw.githubusercontent.com/bitprophet/alabaster/master/docs/changelog.rst').


This is the docker file I've used.
-------------------------
# syntax=docker/dockerfile:1
FROM ubuntu:22.04
LABEL Description="CORE Docker Ubuntu Image"

ARG PREFIX=/usr/local
ARG BRANCH=master
ARG PROTOC_VERSION=3.19.6
ARG VENV_PATH=/opt/core/venv
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="$PATH:${VENV_PATH}/bin"
WORKDIR /opt

# install system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    sudo \
    wget \
    tzdata \
    libpcap-dev \
    libpcre3-dev \
    libprotobuf-dev \
    libxml2-dev \
    protobuf-compiler \
    unzip \
    uuid-dev \
    iproute2 \
    iputils-ping \
    tcpdump && \
    apt-get autoremove -y

# install core
RUN git clone https://github.com/coreemu/core && \
    cd core && \
    git checkout ${BRANCH} && \
    ./setup.sh && \
    . /root/.bashrc && \
    inv install -v -p ${PREFIX} && \
    cd /opt && \
    rm -rf ospf-mdr

WORKDIR /root
-------------------------

**Comment by bharnden** [comment]
I just ran a slightly older variation, albeit from an Ubuntu host, without issue. I would personally try there first, as that is something that has been vetted at the moment.

Otherwise you would need to dig better as to why its getting stuck or not following through, as I do not see that issue myself.

We do not use AUR in any capacity, so whatever issues are there I cannot speak to.

**Comment by rsaSantos** [comment]
Thanks, I'll probably use a Ubuntu VM.
