### ISSUE TITLE
[question] About the computation of throughout put in core.

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#815]
**Describe the bug**
I write a program of flushing packets. The program uses TCP protocol. The sender send packets at 1Mbps and the size of packet is 1000 bytes. The receiver recevices these packets and computes the throughtout put, packet loss rate, delay between two nodes in core.  
However, the outcome of throughout put is bigger than 1Mbps which is the sending rate of the sender when the packet loss rate in whan node is 0. And when the packet loss rate increases, the difference between throughout put and 1Mbps is larger. And I find some packets is divided into more packets. In the thoery, the throughout put is no larger than 1Mps (the sending rate) because some packets may be lost. And I find some packets is divided into more packets.
<img width="415" alt="image" src="https://github.com/coreemu/core/assets/101703577/c4947d5c-e82e-497c-91ba-95d38b0ebdff">
The environment is two MDR nodes linked by a wlan node. One is running sender program and the other one is running receiver program.
 My programs are here:
[flushing_packets.zip](https://github.com/coreemu/core/files/12497165/flushing_packets.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.2]
 - EMANE Version [e.g. 1.2.4]

**Comment by bharnden** [comment]
I would likely depend on existing tooling for sending and measuring packets, rather than creating your own. I will not run your program, but can only assume there are issues with the implementation versus your expectations.

The nodes in a CORE WLAN are connected by a Linux bridge and veth pairs, so how they communicate and packets are sent and received all get handled at a system level and outside of COREs control. The only other aspect will be some `tc` impairments that are implemented against the interfaces being used by the nodes, defined by the WLAN configuration.

**Comment by jxGui** [comment]
Thank you for your help. I will try to use some tools such as MGEN TRPR.
