### ISSUE TITLE
Switch<->Node, Switch<->RJ45 Bandwidth

### ISSUE THREAD

**Issue by rodsantiago** [coreemu/core#88]
The symmetrical bandwidth link effect setting for links that have a switch/hub on one end and a (network layer) node on the other end, is applied only on the switch/hub to node direction. The bandwidth is unlimited in the other direction.

The same issue has been observed for links that have a switch/hub on one end and an RJ45 on the other.

**Comment by bharnden** [comment]
This now is the known behavior and after speaking about it appears to also be the desired behavior.

After some research the reason this behavior occurs is the following. The TC configuration is applied on the veth peer on the host and not on the interface within the container.

Because of this and because TC applies its affects to traffic going out an interface the traffic is seen as going out of the host interface  configured to the containers interface, giving an opposite effect.
